### ISSUE TITLE
Pull to refresh

### ISSUE THREAD

**Issue by yomalsami** [l3lackcurtains/Flutter-for-Wordpress-App#15]
How to implement pull down refresh? Thank you.

**Comment by l3lackcurtains** [comment]
I have a pull-down refresh version implemented. I still have to finalize it. Once it is done I will update.

**Comment by yomalsami** [comment]
Great.

**Comment by yomalsami** [comment]
> I have a pull-down refresh version implemented. I still have to finalize it. Once it is done I will update.

I tried usinh pull to refresh package, but couldnt do it correctly.

**Comment by krishnarajsinh** [comment]
Please share the code here struggling without swipe to refresh feature.

**Comment by l3lackcurtains** [comment]
It is added in the pro version.
