### ISSUE TITLE
chiew and web issue with new sdk update

### ISSUE THREAD

**Issue by tah75** [l3lackcurtains/Flutter-for-Wordpress-App#16]
there is new update for flutter sdk and chiew and webview has been deprecate.

**Comment by bhashid** [comment]
How to fix it.. url and YouTube videos not showing

**Comment by l3lackcurtains** [comment]
consider using a stable channel in flutter for now.

**Comment by l3lackcurtains** [comment]
Upgraded the codebase with flutter 2.5. Check now.
