### ISSUE TITLE
Not able to find launcher dart file

### ISSUE THREAD

**Issue by nalin88** [l3lackcurtains/Flutter-for-Wordpress-App#23]
hey bro please help me i am not able to find this https://raw.githubusercontent.com/l3lackcurtains/Flutter-for-Wordpress-App/master/resources/Screenshot_1.png launcher file so that I can edit and add my own blog logo... please reply me as soon as possible

**Comment by l3lackcurtains** [comment]
Launcher files are located here.
https://github.com/l3lackcurtains/Flutter-for-Wordpress-App/tree/master/android/app/src/main/res/drawable

Just put your logo and design on top of these two images to ensure the exact size and to not mess up.

**Comment by nalin88** [comment]
what is the size of drawable icon.png and splash.png?

**Comment by nalin88** [comment]
thanks a lot
