### ISSUE TITLE
_Type Error

### ISSUE THREAD

**Issue by francisJun** [l3lackcurtains/Flutter-for-Wordpress-App#25]
This is a really good project. I faced this error when debuging:
 Exception has occurred.
_TypeError (type '(dynamic) => Article' is not a subtype of type '(String, dynamic) => MapEntry<dynamic, dynamic>' of 'transform')

The error usually occures when I scroll to the end of a list of post.

![Capture](https://user-images.githubusercontent.com/43418025/89123196-1685db00-d4bd-11ea-83d5-68796242c3b8.PNG)

**Comment by l3lackcurtains** [comment]
Maybe try checking the length of **response.body** before addAll function.

**Comment by francisJun** [comment]
I am very new to flutter and I am learning by building. Can you give a code snipppet on exactly how to do that please?

**Comment by mysps** [comment]
All posts must have a featured image. A condition must be added with a container image if no image is found
