### ISSUE TITLE
DiagnosticableMixin error

### ISSUE THREAD

**Issue by neodavids** [l3lackcurtains/Flutter-for-Wordpress-App#30]
I just downloaded and ran the code (flutter run )  on flutter 1.20 and i got this error.

**Comment by shahryar-cmyk** [comment]
Start by running a,

"flutter clean" command, then included,
flutter_svg: ^0.17.3+1 in pubsepc.yaml followed by a,
"flutter pub get" command. Then run your code to see if you will still get this error. This was what worked for me

**Comment by l3lackcurtains** [comment]
I have updated all the packages..try now. Should work
