### ISSUE TITLE
How to remove fetched short codes from post

### ISSUE THREAD

**Issue by krishnarajsinh** [l3lackcurtains/Flutter-for-Wordpress-App#32]
I have divi plugin which is used to create post. It uses Shortcodes.
This app fetched all shortcodes as well. 
How to remove Shortcodes?                

Ex: [et_pb]

**Comment by l3lackcurtains** [comment]
Use this code in your functions.php file in wordpress.

```php
add_filter( 'rest_prepare_post', 'modify_post_content', 10, 3 );
function modify_post_content( $data, $post, $request ) {
    $_data = $data->data;
    $_data['content']['rendered'] = preg_replace('/\[\/?et_pb.*?\]/', '', $_data['content']['rendered']);
    $data->data = $_data;
    return $data;
}
```

**Comment by krishnarajsinh** [comment]
You saved my life. All the Shortcodes are gone now. Having following issue after that.
**Issue 1:**
**I have following code in website post:**
-------------------------------------------
<div class="et_pb_code_inner"><script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

<ins class="adsbygoogle"
 style="display:block"
 data-ad-client="ca-pub-998213332237281"
 data-ad-slot="2844692053"
 data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script></div>
</div> <div class="et_pb_module et_pb_text et_pb_text_1  et_pb_text_align_left et_pb_bg_layout_light">	
<div class="et_pb_text_inner"><p>Are re are yeh kya hua<br />
e|-0-2-3-0-7-5-3-2—</p>
--------------------------------------
All short code is removed but following line shows.
Result shows in app:

**style="display:block"
 data-ad-client="ca-pub-998213332237281"
 data-ad-slot="2844692053"
 data-ad-format="auto">**Are re are yeh kya hua
e|-0-2-3-0-7-5-3-2—
-------------------------------------------------------------------------------
**Issue 2:**
[et_pb_audio audio="https://www.guitarhindisongs.com/wp-content/uploads/2020/06/Khairiyat.mp3" _builder_version="4.4.8"] [/et_pb_audio]

How to add this audio in post, with short cut this audio is also removed from the fetched post.

Same in Youtube video. How to show video in post.
[et_pb_video src="https://www.youtube.com/watch?v=shmnGc194Vg" _builder_version="4.4.8"] [/et_pb_video]

**Comment by l3lackcurtains** [comment]
Put that script somewhere else like inside the header tag or after the body tag.

For youtube video and audio, use embedded code instead of shortcodes.

**Comment by krishnarajsinh** [comment]
I have more than 400 posts, so it’s quite difficult to remove this script from all post.

This might seems newbie question:

Can we do something like this hardcode to remove specific text:

   $_data['content']['rendered'] = preg_replace('/\[\/?et_pb.*?\]/' && ‘style=“display:block”’, '', $_data['content']['rendered']);
    $data->data = $_data;

**Comment by krishnarajsinh** [comment]
**Issue is solve by changing script code to inline:**

<ins class="adsbygoogle" style="display:block" data-ad-client="ca-pub-998213332237281" data-ad-slot="28446934433" data-ad-format="auto"></ins>
