### ISSUE TITLE
Plugin generate errors while activating

### ISSUE THREAD

**Issue by krishnarajsinh** [l3lackcurtains/Flutter-for-Wordpress-App#37]
The plugin generated 3 characters of unexpected output during activation. If you notice “headers already sent” messages, problems with syndication feeds or other issues, try deactivating or removing this plugin.

**Comment by Tony-Akani** [comment]
Check if you have any plugin that tries to hide your rss feed installed,
And deactivate it, a similar plugin could be WordPress hide posts
