### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Tony-Akani** [l3lackcurtains/Flutter-for-Wordpress-App#38]
Please I encountered and error while trying to run main dart 
Lib/main.dart: 115:61: Error: No named parameter with the name 'label' . BottomNavigationBarItem(icon: Icon(Icons.home), label: 'Home'),

******************************
Context: Found this candidate, 
But the arguments don't match
const BottomNavigationaBarItem({

**Comment by Tony-Akani** [comment]
Please help

**Comment by l3lackcurtains** [comment]
Upgrade your flutter version to latest stable.
And it will work.

**Comment by Tony-Akani** [comment]
Okay thanks I would try that
