### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Tony-Akani** [l3lackcurtains/Flutter-for-Wordpress-App#39]
thanks i just updated to a new flutter version but now i am still having an error, please i am kind of a beginner in flutter and proper guidance would be appreciated,  the app is actually for a client and i need to test that the free version works before buying the pro version
here is the error
Launching lib\main.dart on Infinix X652B in debug mode...
Running Gradle task 'assembleDebug'...
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\TONY\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\webview_flutter-0.3.24\android\src\main\java\io\flutter\plugins\webviewflutter\FlutterWebView.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> Could not resolve all artifacts for configuration ':app:debugCompileClasspath'.
   > Could not download x86_64_debug.jar (io.flutter:x86_64_debug:1.0.0-a1440ca392ca23e874a105c5f3248b495bd0e247)
      > Could not get resource 'https://storage.googleapis.com/download.flutter.io/io/flutter/x86_64_debug/1.0.0-a1440ca392ca23e874a105c5f3248b495bd0e247/x86_64_debug-1.0.0-a1440ca392ca23e874a105c5f3248b495bd0e247.jar'.
         > Read timed out

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8m 3s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by Tony-Akani** [comment]
Flutter doctor
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:/Users/TONY/Desktop/adt-bundle-windows-x86_64-20140321/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:/Users/TONY/Desktop/adt-bundle-windows-x86_64-20140321/sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

**Comment by l3lackcurtains** [comment]
run the command
```bash
flutter clean
```

and run.

**Comment by Tony-Akani** [comment]
Ohh my brother thank you so much it ran Successfully, you have made my day, I would really appreciate if I can get your email so that I can reach out if I am stuck anywhere, I promise to be a good student
