### ISSUE TITLE
Auto-push notification

### ISSUE THREAD

**Issue by FauzyAbdan** [l3lackcurtains/Flutter-for-Wordpress-App#4]
Hi, bro....me again here...

It's just a question (or maybe a request)...

Will this app gets notification when a new article submitted from WP Dashboard? So, the admin doesn't need to go to FCM/GCM Console first to send the push notification to this app.

**Comment by l3lackcurtains** [comment]
No, It requires you to go to GCM to send push notification. But, you can find some WordPress plugins to integrate GCM with WordPress for the auto push notification you want.
