### ISSUE TITLE
Subcategory Support

### ISSUE THREAD

**Issue by shameemreza** [l3lackcurtains/Flutter-for-Wordpress-App#42]
Is your pro version support Subcategory on category listing page?

**Comment by l3lackcurtains** [comment]
Have removed category page.. In search page can put it with image manually.

**Comment by shameemreza** [comment]
Actually its not possible to add manually all the category. If you can add the category page with main and subcategory for pro version, then I might can buy today.

**Comment by l3lackcurtains** [comment]
Purchase it. I will provide you code including the category and subcategory page.

**Comment by shameemreza** [comment]
Hi, Thanks Brother. I already purchased it. But nothing is loading inside the app. I followed your guide and changes everything.
DO you know why?

Also, how I can remove flutter logo from splash screen?

![Screenshot_1605046383](https://user-images.githubusercontent.com/14240438/98742219-3e4bdf80-23d8-11eb-9d21-5f2a098130e2.png)

![Screenshot_1605047551](https://user-images.githubusercontent.com/14240438/98742242-49067480-23d8-11eb-8971-a4d08eb40b59.png)

![Screenshot_1605046019](https://user-images.githubusercontent.com/14240438/98742128-1492b880-23d8-11eb-98a6-f15bc3695ebb.png)

**Comment by shameemreza** [comment]
And also, do I need to worry about this warning?

`Warning
──────────────────────────────────────────────────────────────────────────────
Your Flutter application is created using an older version of the Android
embedding. It's being deprecated in favor of Android embedding v2. Follow the
steps at

https://flutter.dev/go/android-project-migration

to migrate your project.`

**Comment by l3lackcurtains** [comment]
I will update the app in the codecanyon. Will fix all issues.

**Comment by shameemreza** [comment]
When bro? I need to publish my app today.

I also saw many bottom over flow issue.

Also, if ads dont load, content do t show.

Now, I need to show something to my client today. Can you please let me know the fixing of featured images now.

And to be honest, will wait today only, otherwise will send you refund request on codecanyon.

Thanks

**Comment by l3lackcurtains** [comment]
It takes time to reflect changes in codecanyon. You seems to be expert on flutter already.. Why don't you try implement it until the changes.

Code:
https://github.com/l3lackcurtains/Flutter-for-Wordpress-App/blob/de3ee66f4ed19b0060a2ef74ec6e4634acb59eb8/lib/pages/categories.dart

**Comment by shameemreza** [comment]
Actually dont want to touch on your code brother.

by the way, just suggest me one things, so that I can save my project.

Just let me know why featured image is not loading. What to do to resolve it?

![Screenshot_1605157733](https://user-images.githubusercontent.com/14240438/98981334-0368b980-2548-11eb-92d3-bc4d73ebb7b6.png)

**Comment by l3lackcurtains** [comment]
Somehow the plugin seems to be not activated. Your wp-json/wp/v2/posts endpoint should have custom object.

Better clear cache from the Wordpress dashboard and server.

**Comment by shameemreza** [comment]
Just saw that your plugin being deactivated with this error: https://prnt.sc/vi6myz

**Comment by shameemreza** [comment]
Should I add those code manually in functions.php ?

**Comment by l3lackcurtains** [comment]
Yes try that.

**Comment by shameemreza** [comment]
Give me 2 minutes and will get you back with update.

**Comment by shameemreza** [comment]
I added the code in functiuons.php but seems still not working. I also cleared cache from wordpress admin and also on bluehost server as well.

**Comment by shameemreza** [comment]
![Screenshot_2020-11-13-00-57-04-65_0dbec473f3a81509ea35f14890ca69f3.jpg](https://user-images.githubusercontent.com/14240438/98983935-b1c22e00-254b-11eb-8103-48312d740eb0.jpg)

And here has some overflow issues.

**Comment by shameemreza** [comment]
![Screenshot_2020-11-13-00-56-56-56_0dbec473f3a81509ea35f14890ca69f3.jpg](https://user-images.githubusercontent.com/14240438/98984000-c999b200-254b-11eb-9726-331b8a6debc8.jpg)

**Comment by l3lackcurtains** [comment]
The plugin and code seem to be working fine without any issues.

Install it from https://github.com/l3lackcurtains/flutter-for-wordpress-wp-plugin/releases
The issue might be with the conflict with other plugin..
For the overflow problem, change the font size according to your need,

**Comment by shameemreza** [comment]
Ok, Featured image loading on featured section, but on others area it not loading. Like in second tab, category page, single page etc.

Also come new error:

![Screenshot_1605208371](https://user-images.githubusercontent.com/14240438/98985300-8dffe780-254d-11eb-8dba-3990fa53178b.png)

**Comment by l3lackcurtains** [comment]
You must have messed up somewhere. Uninstall and install app.. and try.

**Comment by shameemreza** [comment]
I didn't touch on your app code bro, this I can assure you. I only changed ads id, one signal id, site url, change color and iamges.

**Comment by shameemreza** [comment]
last time also faced this and started newly resolved it. Looks like need o re download and do everything again.

**Comment by l3lackcurtains** [comment]
Okay cool. Try it.

**Comment by shameemreza** [comment]
Oh one things,

Do I need to use anything to add profile avatar? Cause I dont see the avatar image, its blank.

**Comment by l3lackcurtains** [comment]
In wordpress dashboard setting section you can change avatar type.

**Comment by l3lackcurtains** [comment]
https://github.com/l3lackcurtains/Flutter-for-Wordpress-App/tree/master/android/app/src/main/res/drawable

Change splash.png and icon.png

**Comment by shameemreza** [comment]
Actually I want to make full screen splash image and dont want to use small icon at the bottom. But I didn't find the code where did you added it in Lib folder.

Will please let me know how I can use full screen image as splash?

**Comment by l3lackcurtains** [comment]
Just remove the image from launch_background.xml file

**Comment by shameemreza** [comment]
ok, what about full screen splash image?

You added splash manually, I mean directly. Why you are not using flutter way?

**Comment by l3lackcurtains** [comment]
flutter way.. app will load the first page at a slow pace.
