### ISSUE TITLE
Notification is opening in browser instead inside the app

### ISSUE THREAD

**Issue by shameemreza** [l3lackcurtains/Flutter-for-Wordpress-App#43]
Hi, Do you have any solution why the notification opening in browser? It should open inside the app, isnt it?

**Comment by l3lackcurtains** [comment]
Use one signal notification.. In wp website.. That will let you to app.

**Comment by shameemreza** [comment]
Did you understand what I asked?

I asked that, once I am sending notifications, app receiving it. But once I am clicking on it, its opening in browser instead in mobile app.

As per normal system, once someone click on notifications, normally that open inside app. But you open it in browser.

Honestly brother, you used very poor and nobe coding standard. For premium product, everything should have in high class.

Its very hard to find your function, method and rest. You used provider but didn't follow its standard as well.

By the way, dont take my words in other way. Just felt irritating on your products.

Now could you please tell, how can I open the notifications click event inside the app.

Means once I will publish post, user getting notifications. Once user will click on the notifications, the post should open inside app, not in browser.

Hope now you are clear.

Thank You.

**Comment by l3lackcurtains** [comment]
Don't expect the standard for 29$ app.. lol.. anyway it is perfectly working for my projects.. you need to learn things..

**Comment by l3lackcurtains** [comment]
anyways,
Use the one signal func in your wp website...

[https://github.com/l3lackcurtains/flutter-for-wordpress-wp-plugin/blob/master/flutter_for_wp.php](https://github.com/l3lackcurtains/flutter-for-wordpress-wp-plugin/blob/master/flutter_for_wp.php)

**Comment by shameemreza** [comment]
ha ha, You have not only have lack of knowledge but also have lack of manner.

You should improve your soft skills bro. It will help you to grow your career, mindset and mentality.

By the way, Thanks for all your kind reply.
