### ISSUE TITLE
Blog Posts not loading into the app

### ISSUE THREAD

**Issue by Steven-Graham** [l3lackcurtains/Flutter-for-Wordpress-App#45]
Good Afternoon,

I am having trouble getting my Wordpress blog to propagate into the Flutter for wordpress app. 
Can you provide instructions on how you found the Featured ID and Page2 Category ID? My Post ID is 4 and the blog page is active but I'm not sure why it's not playing. 

// Featured category ID (for Home Screen top section)
const int FEATURED_ID = 4;

// Tab 2 page category name
const String PAGE2_CATEGORY_NAME = "Lifestyle";

// Tab 2 page category ID
const int PAGE2_CATEGORY_ID = 4;

Any help would be greatly appreciated.
Thanks, 

Steve @ Gozy Mobile Solutions

**Comment by l3lackcurtains** [comment]
Go to the category page and in the URL you can find the ID. 
For featured ID, add a category called "featured" and use it.
