### ISSUE TITLE
Problem loading website

### ISSUE THREAD

**Issue by tolysim** [l3lackcurtains/Flutter-for-Wordpress-App#47]
Hey,
Using a pro version.
After changing "WORDPRESS_URL" a demo url to my site url, the pro application showing no Internet error, a free version working fine.

site url:
const String WORDPRESS_URL = "https://avreviews.co.il";
const int FEATURED_ID = 509;

Error:
E/flutter (14270): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: Class 'String' has no instance method 'map'.
E/flutter (14270): Receiver: "[{\"id\":14577,\"date\":\"2021-01-12T19:55:00\",\"link\":\"https:\\/\\/avreviews.co

**Comment by l3lackcurtains** [comment]
install plugin as instructed in wordpress website.. and in url use http instead of https

**Comment by l3lackcurtains** [comment]
Please install the plugins as instructed in your wordpress website. Also, in WORDPRESS_URL use "http" instead of "https".

**Comment by tolysim** [comment]
Hey, 
I have already did those steps at my first try, and for to be on the safe side I did it again, any change...
The same site URL working with free version, and does not working with the pro.
