### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by bal3m** [l3lackcurtains/Flutter-for-Wordpress-App#7]
Hello, I tried to run app at first time an I got this error:

      > Cannot find a version of 'androidx.annotation:annotation' that satisfies the version constraints: 
           Dependency path 'io.flutter.plugins.urllauncher:url_launcher:1.0-SNAPSHOT' --> 'androidx.annotation:annotation:1.1.0'
           Constraint path 'io.flutter.plugins.urllauncher:url_launcher:1.0-SNAPSHOT' --> 'androidx.annotation:annotation:{strictly 1.0.0}' because of the following reason: debugRuntimeClasspath uses version 1.0.0
           Dependency path 'io.flutter.plugins.urllauncher:url_launcher:1.0-SNAPSHOT' --> 'io.flutter:flutter_embedding_debug:1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695' --> 'androidx.annotation:annotation:1.0.0'
           Dependency path 'io.flutter.plugins.urllauncher:url_launcher:1.0-SNAPSHOT' --> 'io.flutter:flutter_embedding_debug:1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695' --> 'androidx.lifecycle:lifecycle-common:2.0.0' --> 'androidx.annotation:annotation:1.0.0'
           Dependency path 'io.flutter.plugins.urllauncher:url_launcher:1.0-SNAPSHOT' --> 'io.flutter:flutter_embedding_debug:1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695' --> 'androidx.lifecycle:lifecycle-common-java8:2.0.0' --> 'androidx.annotation:annotation:1.0.0'
           Dependency path 'io.flutter.plugins.urllauncher:url_launcher:1.0-SNAPSHOT' --> 'io.flutter:flutter_embedding_debug:1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695' --> 'androidx.lifecycle:lifecycle-runtime:2.0.0' --> 'androidx.annotation:annotation:1.0.0'
           Dependency path 'io.flutter.plugins.urllauncher:url_launcher:1.0-SNAPSHOT' --> 'io.flutter:flutter_embedding_debug:1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695' --> 'androidx.fragment:fragment:1.0.0' --> 'androidx.annotation:annotation:1.0.0'
           Dependency path 'io.flutter.plugins.urllauncher:url_launcher:1.0-SNAPSHOT' --> 'io.flutter:flutter_embedding_debug:1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695' --> 'androidx.lifecycle:lifecycle-runtime:2.0.0' --> 'androidx.arch.core:core-common:2.0.0' --> 'androidx.annotation:annotation:1.0.0'
           Dependency path 'io.flutter.plugins.urllauncher:url_launcher:1.0-SNAPSHOT' --> 'io.flutter:flutter_embedding_debug:1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695' --> 'androidx.fragment:fragment:1.0.0' --> 'androidx.core:core:1.0.0' --> 'androidx.annotation:annotation:1.0.0'
           Dependency path 'io.flutter.plugins.urllauncher:url_launcher:1.0-SNAPSHOT' --> 'io.flutter:flutter_embedding_debug:1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695' --> 'androidx.fragment:fragment:1.0.0' --> 'androidx.legacy:legacy-support-core-ui:1.0.0' --> 'androidx.annotation:annotation:1.0.0'
           Dependency path 'io.flutter.plugins.urllauncher:url_launcher:1.0-SNAPSHOT' --> 'io.flutter:flutter_embedding_debug:1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695' --> 'androidx.fragment:fragment:1.0.0' --> 'androidx.legacy:legacy-support-core-utils:1.0.0' --> 'androidx.annotation:annotation:1.0.0'
           Dependency path 'io.flutter.plugins.urllauncher:url_launcher:1.0-SNAPSHOT' --> 'io.flutter:flutter_embedding_debug:1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695' --> 'androidx.fragment:fragment:1.0.0' --> 'androidx.loader:loader:1.0.0' --> 'androidx.annotation:annotation:1.0.0'
           Dependency path 'io.flutter.plugins.urllauncher:url_launcher:1.0-SNAPSHOT' --> 'io.flutter:flutter_embedding_debug:1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695' --> 'androidx.fragment:fragment:1.0.0' --> 'androidx.lifecycle:lifecycle-viewmodel:2.0.0' --> 'androidx.annotation:annotation:1.0.0'
           Dependency path 'io.flutter.plugins.urllauncher:url_launcher:1.0-SNAPSHOT' --> 'io.flutter:flutter_embedding_debug:1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695' --> 'androidx.fragment:fragment:1.0.0' --> 'androidx.core:core:1.0.0' --> 'androidx.collection:collection:1.0.0' --> 'androidx.annotation:annotation:1.0.0'
           Dependency path 'io.flutter.plugins.urllauncher:url_launcher:1.0-SNAPSHOT' --> 'io.flutter:flutter_embedding_debug:1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695' --> 'androidx.fragment:fragment:1.0.0' --> 'androidx.core:core:1.0.0' --> 'androidx.versionedparcelable:versionedparcelable:1.0.0' --> 'androidx.annotation:annotation:1.0.0'
           Dependency path 'io.flutter.plugins.urllauncher:url_launcher:1.0-SNAPSHOT' --> 'io.flutter:flutter_embedding_debug:1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695' --> 'androidx.fragment:fragment:1.0.0' --> 'androidx.legacy:legacy-support-core-ui:1.0.0' --> 'androidx.customview:customview:1.0.0' --> 'androidx.annotation:annotation:1.0.0'
           Dependency path 'io.flutter.plugins.urllauncher:url_launcher:1.0-SNAPSHOT' --> 'io.flutter:flutter_embedding_debug:1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695' --> 'androidx.fragment:fragment:1.0.0' --> 'androidx.legacy:legacy-support-core-ui:1.0.0' --> 'androidx.viewpager:viewpager:1.0.0' --> 'androidx.annotation:annotation:1.0.0'
           Dependency path 'io.flutter.plugins.urllauncher:url_launcher:1.0-SNAPSHOT' --> 'io.flutter:flutter_embedding_debug:1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695' --> 'androidx.fragment:fragment:1.0.0' --> 'androidx.legacy:legacy-support-core-ui:1.0.0' --> 'androidx.coordinatorlayout:coordinatorlayout:1.0.0' --> 'androidx.annotation:annotation:1.0.0'
           Dependency path 'io.flutter.plugins.urllauncher:url_launcher:1.0-SNAPSHOT' --> 'io.flutter:flutter_embedding_debug:1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695' --> 'androidx.fragment:fragment:1.0.0' --> 'androidx.legacy:legacy-support-core-ui:1.0.0' --> 'androidx.drawerlayout:drawerlayout:1.0.0' --> 'androidx.annotation:annotation:1.0.0'
           Dependency path 'io.flutter.plugins.urllauncher:url_launcher:1.0-SNAPSHOT' --> 'io.flutter:flutter_embedding_debug:1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695' --> 'androidx.fragment:fragment:1.0.0' --> 'androidx.legacy:legacy-support-core-ui:1.0.0' --> 'androidx.slidingpanelayout:slidingpanelayout:1.0.0' --> 'androidx.annotation:annotation:1.0.0'
           Dependency path 'io.flutter.plugins.urllauncher:url_launcher:1.0-SNAPSHOT' --> 'io.flutter:flutter_embedding_debug:1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695' --> 'androidx.fragment:fragment:1.0.0' --> 'androidx.legacy:legacy-support-core-ui:1.0.0' --> 'androidx.interpolator:interpolator:1.0.0' --> 'androidx.annotation:annotation:1.0.0'
           Dependency path 'io.flutter.plugins.urllauncher:url_launcher:1.0-SNAPSHOT' --> 'io.flutter:flutter_embedding_debug:1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695' --> 'androidx.fragment:fragment:1.0.0' --> 'androidx.legacy:legacy-support-core-ui:1.0.0' --> 'androidx.swiperefreshlayout:swiperefreshlayout:1.0.0' --> 'androidx.annotation:annotation:1.0.0'
           Dependency path 'io.flutter.plugins.urllauncher:url_launcher:1.0-SNAPSHOT' --> 'io.flutter:flutter_embedding_debug:1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695' --> 'androidx.fragment:fragment:1.0.0' --> 'androidx.legacy:legacy-support-core-ui:1.0.0' --> 'androidx.asynclayoutinflater:asynclayoutinflater:1.0.0' --> 'androidx.annotation:annotation:1.0.0'
           Dependency path 'io.flutter.plugins.urllauncher:url_launcher:1.0-SNAPSHOT' --> 'io.flutter:flutter_embedding_debug:1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695' --> 'androidx.fragment:fragment:1.0.0' --> 'androidx.legacy:legacy-support-core-ui:1.0.0' --> 'androidx.cursoradapter:cursoradapter:1.0.0' --> 'androidx.annotation:annotation:1.0.0'
           Dependency path 'io.flutter.plugins.urllauncher:url_launcher:1.0-SNAPSHOT' --> 'io.flutter:flutter_embedding_debug:1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695' --> 'androidx.fragment:fragment:1.0.0' --> 'androidx.legacy:legacy-support-core-utils:1.0.0' --> 'androidx.documentfile:documentfile:1.0.0' --> 'androidx.annotation:annotation:1.0.0'
           Dependency path 'io.flutter.plugins.urllauncher:url_launcher:1.0-SNAPSHOT' --> 'io.flutter:flutter_embedding_debug:1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695' --> 'androidx.fragment:fragment:1.0.0' --> 'androidx.legacy:legacy-support-core-utils:1.0.0' --> 'androidx.localbroadcastmanager:localbroadcastmanager:1.0.0' --> 'androidx.annotation:annotation:1.0.0'
           Dependency path 'io.flutter.plugins.urllauncher:url_launcher:1.0-SNAPSHOT' --> 'io.flutter:flutter_embedding_debug:1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695' --> 'androidx.fragment:fragment:1.0.0' --> 'androidx.legacy:legacy-support-core-utils:1.0.0' --> 'androidx.print:print:1.0.0' --> 'androidx.annotation:annotation:1.0.0'
           Dependency path 'io.flutter.plugins.urllauncher:url_launcher:1.0-SNAPSHOT' --> 'io.flutter:flutter_embedding_debug:1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695' --> 'androidx.fragment:fragment:1.0.0' --> 'androidx.loader:loader:1.0.0' --> 'androidx.lifecycle:lifecycle-livedata:2.0.0' --> 'androidx.arch.core:core-runtime:2.0.0' --> 'androidx.annotation:annotation:1.0.0'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

**Comment by moelfassi** [comment]
do you have the latest flutter?

**Comment by bal3m** [comment]
My version is 1.12.13??

**Comment by bal3m** [comment]
I found it!
When I ran package upgrade, the problem was solved.
